language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "UHdkWIc3BN709EFyVs7fgjsg9rtereceYrPh9YWL4EGQurGPXDb1+sW5hAhoLU2ch5tHwIQpp0NVH+tnevCsbsdDPjeLBIcK+UHkdDAIxRr+DQYpaTYNWK1tzzKeTRZICYE1jlp6Ryvzd8iqPCPm5b1Eryb9FtTYP5qYsvg3s24="

addons:
  coverity_scan:
    project:
      name: "davidmoten/rtree"
      description: "RTree java implementation with reactive api"
    notification_email: davidmoten@gmail.com
    build_command_prepend: ""
    build_command:   "mvn install -B -Dmaven.javadoc.skip=true"
    branch_pattern: coverity_scan
